**SALES DATA ANALYSIS AND DASHBOARD**

Step 1: Dataset loading and exploration

In [1]:
import pandas as pd

df= pd.read_csv('/content/global_ecommerce_sales.csv')
df.head()

,Order_ID,Order_Date,Customer_Name,Customer_Segment,Country,Region,Product_Category,Product_Name,Quantity,Unit_Price,Discount_Percent,Total_Sales,Shipping_Cost,Profit,Payment_Method
0,ORD-11121,2023-01-02,Karen Suzuki,Corporate,United States,North America,Technology,Wireless Bluetooth Headphones,3,99.43,0,298.29,9.31,124.92,Cash on Delivery
1,ORD-11244,2023-01-02,John Johansson,Corporate,Spain,Europe,Technology,Mechanical Gaming Keyboard,4,97.93,20,313.38,14.31,83.62,Cash on Delivery
2,ORD-10325,2023-01-03,Jessica Garcia,Consumer,Mexico,North America,Office Supplies,Binder Clips Assorted 48pc,2,10.74,0,21.48,8.12,3.69,Credit Card
3,ORD-10467,2023-01-03,Clara Taylor,Corporate,Italy,Europe,Technology,Webcam HD 1080p,2,61.86,15,105.16,10.79,26.32,PayPal
4,ORD-11454,2023-01-05,Felix Thomas,Consumer,Italy,Europe,Furniture,Standing Desk Converter,4,330.67,20,1058.14,11.09,253.44,Credit Card

In [2]:
print('Rows and Columns:', df.shape)
print('\nColumn names;')
print(df.columns.tolist())

Rows and Columns: (2000, 15)

Column names;
['Order_ID', 'Order_Date', 'Customer_Name', 'Customer_Segment', 'Country', 'Region', 'Product_Category', 'Product_Name', 'Quantity', 'Unit_Price', 'Discount_Percent', 'Total_Sales', 'Shipping_Cost', 'Profit', 'Payment_Method']

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order_ID          2000 non-null   object
 1   Order_Date        2000 non-null   object
 2   Customer_Name     2000 non-null   object
 3   Customer_Segment  2000 non-null   object
 4   Country           2000 non-null   object
 5   Region            2000 non-null   object
 6   Product_Category  2000 non-null   object
 7   Product_Name      2000 non-null   object
 8   Quantity          2000 non-null   int64
 9   Unit_Price        2000 non-null   float64
 10  Discount_Percent  2000 non-null   int64
 11  Total_Sales       2000 non-null   float64
 12  Shipping_Cost     2000 non-null   float64
 13  Profit            2000 non-null   float64
 14  Payment_Method    2000 non-null   object
dtypes: float64(4), int64(2), object(9)
memory usage: 234.5+ KB

In [4]:
df.describe()

,Quantity,Unit_Price,Discount_Percent,Total_Sales,Shipping_Cost,Profit
count,2000.000000,2000.000000,2000.000000,2000.000000,2000.00000,2000.000000
mean,3.557500,73.329490,8.572500,242.279670,12.90212,79.436160
std,2.704506,79.311014,7.261274,382.583802,5.22319,137.573593
min,1.000000,3.030000,0.000000,2.420000,5.52000,-11.280000
25%,2.000000,18.757500,0.000000,41.227500,9.45750,6.865000
50%,3.000000,46.420000,10.000000,113.125000,11.84500,32.830000
75%,5.000000,90.250000,15.000000,266.552500,14.92000,90.297500
max,15.000000,472.560000,30.000000,3813.980000,40.44000,1373.630000

**Data Cleaning**

Step 2: Missing values analysis

In [5]:
df.isnull().sum()

Order_ID            0
Order_Date          0
Customer_Name       0
Customer_Segment    0
Country             0
Region              0
Product_Category    0
Product_Name        0
Quantity            0
Unit_Price          0
Discount_Percent    0
Total_Sales         0
Shipping_Cost       0
Profit              0
Payment_Method      0
dtype: int64

Step 3: Duplicate-value analysis

In [8]:
df.duplicated().sum()

np.int64(0)

In [6]:
df.dtypes

Order_ID             object
Order_Date           object
Customer_Name        object
Customer_Segment     object
Country              object
Region               object
Product_Category     object
Product_Name         object
Quantity              int64
Unit_Price          float64
Discount_Percent      int64
Total_Sales         float64
Shipping_Cost       float64
Profit              float64
Payment_Method       object
dtype: object

In [7]:
df['Order_Date']= pd.to_datetime(df['Order_Date'])
df.dtypes

Order_ID                    object
Order_Date          datetime64[ns]
Customer_Name               object
Customer_Segment            object
Country                     object
Region                      object
Product_Category            object
Product_Name                object
Quantity                     int64
Unit_Price                 float64
Discount_Percent             int64
Total_Sales                float64
Shipping_Cost              float64
Profit                     float64
Payment_Method              object
dtype: object

In [8]:
print('Start date:',df['Order_Date'].min())
print('End date:',df['Order_Date'].max())

Start date: 2023-01-02 00:00:00
End date: 2025-12-31 00:00:00

Step 4: Key Performance Indicator.

In [9]:
print('Total Sales:',df['Total_Sales'].sum())
print('Total Profit: ', df['Profit'].sum())
print('Total Quantity Sold:', df['Quantity'].sum())
print('Total Orders:', df['Order_ID'].nunique())
print('Total Customers:', df['Customer_Name'].nunique())

Total Sales: 484559.33999999997
Total Profit:  158872.32
Total Quantity Sold: 7115
Total Orders: 2000
Total Customers: 1534

In [18]:
#average_order_value= df['Total_Sales'].mean()
#rint('Average Order Value:', average_order_value)

Average Order Value: 242.27966999999998

In [10]:
average_order_value=df['Total_Sales'].sum()/df['Order_ID'].nunique()
print('Average Order Value:', average_order_value)

Average Order Value: 242.27966999999998

**SALES BY  PRODUCT CATEGORY**

In [11]:
category_sales=df.groupby('Product_Category')['Total_Sales'].sum()
print('Category Sales:')
print(category_sales)

Category Sales:
Product_Category
Clothing & Accessories     69375.63
Furniture                 256274.68
Office Supplies            19390.81
Technology                139518.22
Name: Total_Sales, dtype: float64

**PROFIT BY PRODUCT CATEGORY**

In [12]:
category_profit=df.groupby('Product_Category')['Profit'].sum()
print('Category Profit:')
print(category_profit)

Category Profit:
Product_Category
Clothing & Accessories    26112.94
Furniture                 81171.57
Office Supplies            3319.16
Technology                48268.65
Name: Profit, dtype: float64

**SALES BY REGION**

In [13]:
region_sales=df.groupby('Region')['Total_Sales'].sum().sort_values(ascending=False)
print('Region Sales:')
print(region_sales)

Region Sales:
Region
Europe                  137006.20
North America           133876.38
Asia Pacific            121707.51
South America            46051.13
Middle East & Africa     45918.12
Name: Total_Sales, dtype: float64

**PROFIT BY REGION**

In [14]:
region_profit=df.groupby('Region')['Profit'].sum().sort_values(ascending=False)
print('Region Profit:')
print(region_profit)

Region Profit:
Region
Europe                  45672.16
North America           45250.09
Asia Pacific            39116.61
South America           14680.98
Middle East & Africa    14152.48
Name: Profit, dtype: float64

**Top 10 Products By Sales**

In [25]:
product_sales=df.groupby('Product_Name')['Total_Sales'].sum().sort_values(ascending=False).head(10)
print('Top 10 Products by Sales:')
print(product_sales)

Top 10 Products by Sales:
Product_Name
Standing Desk Converter          46614.22
Ergonomic Office Chair           45405.15
Corner L-Shaped Desk             41070.48
Mesh Back Task Chair             38179.77
Wireless Bluetooth Headphones    28258.70
Mechanical Gaming Keyboard       24072.42
Filing Cabinet 3-Drawer          23108.01
Folding Table Portable           18663.13
Portable External SSD 1TB        18065.30
Bookshelf 5-Tier                 17741.59
Name: Total_Sales, dtype: float64

**Customer Segment analysis**

In [18]:
segment_sales=df.groupby('Customer_Segment')['Total_Sales'].sum().sort_values(ascending=False)
print('Customer Segment Sales:')
print(segment_sales)

Customer Segment Sales:
Customer_Segment
Consumer       256287.74
Corporate      146050.39
Home Office     82221.21
Name: Total_Sales, dtype: float64

In [17]:
segment_profit=df.groupby('Customer_Segment')['Profit'].sum().sort_values(ascending=False)
print('Customer Segment Profit:')
print(segment_profit)

Customer Segment Profit:
Customer_Segment
Consumer       87300.36
Corporate      44463.44
Home Office    27108.52
Name: Profit, dtype: float64

**Monthly Sales Analysis**

In [19]:
df['Order_Date']=pd.to_datetime(df['Order_Date'])
df['Month']=df['Order_Date'].dt.month
monthly_sales=df.groupby('Month')['Total_Sales'].sum()
print('Monthly Sales:')
print(monthly_sales)

Monthly Sales:
Month
1     31611.59
2     36260.55
3     34378.89
4     44203.66
5     42434.47
6     43694.85
7     45671.22
8     34157.01
9     36002.05
10    51095.40
11    39669.78
12    45379.87
Name: Total_Sales, dtype: float64

In [20]:
df['Order_Date'] = pd.to_datetime(df['Order_Date'])

monthly_profit = df.groupby(df['Order_Date'].dt.month)['Profit'].sum()

print('Monthly Profit:')
print(monthly_profit)

Monthly Profit:
Order_Date
1     10372.92
2     12542.07
3     11791.68
4     14656.51
5     14198.57
6     13769.20
7     15124.83
8     11237.37
9     11393.93
10    16596.90
11    12635.31
12    14553.03
Name: Profit, dtype: float64

**Payment Method analysis**

In [21]:
payment_sales = df.groupby('Payment_Method')['Total_Sales'].sum()

print('Sales by Payment Method:')
print(payment_sales)

Sales by Payment Method:
Payment_Method
Bank Transfer        71599.04
Cash on Delivery     77129.54
Credit Card         192717.89
PayPal              143112.87
Name: Total_Sales, dtype: float64

In [32]:
payment_profit = df.groupby('Payment_Method')['Profit'].sum()

print('Profit by Payment Method:')
print(payment_profit)

Profit by Payment Method:
Payment_Method
Bank Transfer       23555.39
Cash on Delivery    25704.89
Credit Card         62323.24
PayPal              47288.80
Name: Profit, dtype: float64

Q**uantity Sold by Product Category**

In [33]:
category_quantity = df.groupby('Product_Category')['Quantity'].sum()

print('Quantity Sold by Category:')
print(category_quantity)

Quantity Sold by Category:
Product_Category
Clothing & Accessories    1551
Furniture                 1806
Office Supplies           1741
Technology                2017
Name: Quantity, dtype: int64

**Sales by Country**

In [34]:
country_sales = df.groupby('Country')['Total_Sales'].sum().sort_values(ascending=False)

print('Sales by Country:')
print(country_sales)

Sales by Country:
Country
Mexico            47217.30
Canada            45326.55
United States     41332.53
Japan             30950.19
United Kingdom    30185.46
Germany           28989.73
China             28322.85
Italy             27484.38
France            26616.81
Australia         25287.72
Spain             23729.82
South Korea       18745.21
Brazil            18473.97
India             18401.54
Argentina         17717.00
Saudi Arabia      13680.22
South Africa      13564.80
Nigeria            9899.91
Colombia           9860.16
UAE                8773.19
Name: Total_Sales, dtype: float64

**Profit by Country**

In [35]:
country_profit = df.groupby('Country')['Profit'].sum().sort_values(ascending=False)

print("Profit by Country:")
print(country_profit)

Profit by Country:
Country
Mexico            15949.44
Canada            15320.95
United States     13979.70
United Kingdom    10185.32
Japan              9826.31
Germany            9518.07
Italy              9125.06
China              9028.07
France             8973.46
Australia          8072.37
Spain              7870.25
South Korea        6124.07
India              6065.79
Brazil             5869.63
Argentina          5731.06
Saudi Arabia       4276.09
South Africa       4072.59
Colombia           3080.29
Nigeria            3031.61
UAE                2772.19
Name: Profit, dtype: float64

In [22]:
df.to_csv('/content/Week2_Sales_Data_Cleaned.csv', index=False)

print("Cleaned dataset exported successfully!")

Cleaned dataset exported successfully!